thruster_manager:
  tf_prefix: openrov
  base_link: base_link
  thruster_topic_prefix: thrusters/
  thruster_topic_suffix: /input
  thruster_frame_base: thruster_
  max_thrust: 100.0
  timeout: -1
  update_rate: 50
  conversion_fcn: proportional
  conversion_fcn_params:
    gain: 1.0